"""empty message

Revision ID: 825553c773f1
Revises: 
Create Date: 2020-06-10 21:38:36.872926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825553c773f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('passwork', sa.String(length=128), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='Gender'), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
